language: node_js
node_js:
    - 14

cache: npm

install:
    - npm install

before_deploy:
    - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: dist
    on:
        branch: gh-pages